
language: python

python:
  - { PATH: "{{Python37}}", VERSION: 3.7, DIST: std, PYINT: python3.7 }
  
virtualenv:
  - path: {{ospathjoin(root_path, pickname("$NAME_JENKINS", project_name + "_$VERSION_$DIST_$NAME"), "_venv")}}
  
install:
  - $PYINT -m pip install --upgrade pip
  - $PYINT -m pip install --no-cache-dir --upgrade --no-deps --index http://localhost:8067/simple/ jyquickhelper pyquickhelper pyensae pymmails pymyinstall pyrsslocal ensae_teaching_cs --extra-index-url=https://pypi.python.org/simple/
  - $PYINT --version
  - $PYINT -m pip freeze

script:
  #- { CMD: "$PYINT -u copy_site.py 1", NAME: "BLOG_1", CLEAN: "0" }
  - { CMD: "$PYINT -u copy_site.py 2", NAME: "BLOG_2", CLEAN: "0" }
